name: EtheriaCore
version: '${project.version}'
main: cykuta.etheriacore.EtheriaCore
api-version: 1.18
authors: [ Cykuta ]
commands:
  tpa:
    description: Send a teleport request to someone user
    permission: core.tp
    usage: "/tpa <player>"
    aliases: [teleport]
  tpaccept:
    description: Accepts a pending teleport request
    permission: core.tp
    aliases: [aceptar, accept]
  tpdeny:
    description: Deny a pending teleport request
    permission: core.tp
    aliases: [denegar, deny]
  creative:
    description: Change your gamemode
    permission: core.gamemode.creative
    aliases: [gmc]
  survival:
    description: Change your gamemode
    permission: core.gamemode.survival
    aliases: [gms]
  adventure:
    description: Change your gamemode
    permission: core.gamemode.adventure
    aliases: [gma]
  spectator:
    description: Change your gamemode
    permission: core.gamemode.spectator
    aliases: [gmsp]
  day:
    description: Change time to day
    permission: core.gamemode.spectator
    usage: "/day <world>"
    aliases: [dia]
  night:
    description: Change time to night
    permission: core.gamemode.spectator
    usage: "/night <world>"
    aliases: [noche]