name: EtheriaCore
version: '${project.version}'
main: cykuta.etheriacore.EtheriaCore
api-version: 1.18
authors: [ Cykuta ]
commands:
  tpa:
    description: Make a teleport request to someone user
    permission: core.tp
    aliases: [teleport]
  tpaccept:
    description: Accepts a pending teleport request
    permission: core.tp
    aliases: [aceptar, accept]
  tpdeny:
    description: Deny a pending teleport request
    permission: core.tp
    aliases: [denegar, deny]