name: EtheriaCore
version: '${project.version}'
main: cykuta.etheriacore.EtheriaCore
api-version: 1.18
authors: [ Cykuta ]
commands:
  tpa:
    description: Send a teleport request to someone user
    permission: core.tp
    aliases: [teleport]
  tpaccept:
    description: Accepts a pending teleport request
    permission: core.tp
    aliases: [aceptar, accept]
  tpdeny:
    description: Deny a pending teleport request
    permission: core.tp
    aliases: [denegar, deny]
  creative:
    description: Changue your gamemode
    permission: core.gamemode.creative
    aliases: [gmc]
  survival:
    description: Changue your gamemode
    permission: core.gamemode.survival
    aliases: [gms]
  adventure:
    description: Changue your gamemode
    permission: core.gamemode.adventure
    aliases: [gma]
  spetator:
    description: Changue your gamemode
    permission: core.gamemode.spectator
    aliases: [gmsp]